# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-22 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
